version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: abc
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  app:
    build: .
    restart: on-failure
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: pass
      DB_DATABASE: abc
    ports:
      - "8501:8501"
    depends_on:
      - db
    volumes:
      - ./:/app:cached

volumes:
  db-data:
